graphNode:
  hostname: http://localhost:8000
  indexer: http://localhost:8030/graphql
  subgraphs:
    - name: notional-finance/local
      pollingInterval: 60000
      longPollingInterval: 1800000
      maxBlockLag: 1

ethNode:
  hostname: http://localhost:8545
  network: local
  retries: 3
  pollingIntervalMs: 10000

liquiditySources:
  - name: uniswapFlashLoan
    type: UNI_FlashSwap
    params:
      factory: '0x6f84742680311CEF5ba42bc10A71a4708b4561d1'
      pairs:
        - DAI-WETH
  - name: walletSource
    type: Wallet
    params:
      address: '0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1'

app:
  port: 7879
  apiVersion: 'v1'
  enableRoutes:
    - liquidator
  metrics:
    enabled: true
    prefix: 'notional_agent'
    defaultMetricsInterval: 10000
    includeQueryParams: true
    maxBlockLag: 1